- src/Console/Rank.hs
- src/General/Util.hs
- src/Recipe/All.hs
- src/Recipe/Cabal.hs
- src/Web/Response.hs
- src/Web/Server.hs
The only controversial change in in `Cabal.hs`, see comment.
> Update to GHC 7.10 and Cabal 1.22.

- html/hoogle.css
Results page should look a bit better after applying this CSS update.
> Fixed CSS overflow problem for results

- README.md
Fixed the formatting on the folder list to match markdown specification.
> Fixed formatting for folder list

- src/Action/CmdLine.hs
- src/Action/Search.hs
It could be helpful for inconvenience described in my blog post: http://przybyszd.blogspot.com/2016/01/easy-hoogle-usage-from-bash.html
> Add numbers option

- src/Action/Search.hs
Conforming to impossibly strict standards ;)
> minor styling changes

- src/Recipe/Haddock.hs
this is fixed in hoogle5 and the part of fixLine function is from there
> remove brackets around symbols produced by haddock

- src/Hoogle/DataBase/SubstrSearch.hs
> fix search for strings longer than 255char

- cbits/text_search.c
- hoogle.cabal
- src/Action/CmdLine.hs
- src/Action/Server.hs
- src/General/Web.hs
this has been done for hoogle4 in #159
> enable support for IPv6

- hoogle.cabal
- src/Action/CmdLine.hs
- src/Action/Server.hs
- src/General/Web.hs
porting #156 from hoogle4 to hoogle5
> add option to run hoogle5 server over TLS

- README.md
pull request hrs/engine#29 filed
> hint at engine-mode

- hoogle.cabal
- src/Action/Server.hs
- src/General/Web.hs
- src/Input/Item.hs
not sure if this is what you intended but I started to work on JSON support for hoogle 5 server.
this is by no means complete but I guess it's better to share it with you now to avoid duplicate work.
this uses the aeson parser/encoder and just implements the `ToJSON` typeclass for `Target`
> [add] rough json support

- hoogle.cabal
- src/Input/Settings.hs
Just tested on our build server, and it seems to solve the problem.
> Make misc/settings.txt file optional #165

- hoogle.cabal
- src/Input/Item.hs
Hello! Are you willing to allow this kind of CPP compatibility shimming?
> allow haskell-src-exts 1.19

- hoogle.cabal
Fixes #234. Would be nice if you could also make a Hackage revision.
> Add an upper bound on http-conduit.

- src/Action/Generate.hs
Noticed while running `hoogle generate`
> Fix typo in Generate.hs

- src/Input/Item.hs
I was working on a [client](https://github.com/meck/alfred-hoogle) for Hoogle as part of learning Haskell, and noticed that it would be good to have a ready Instance of fromJSON when I was using the Hoogle library for a json web client.
> Added FromJSON instance for Target

- src/Action/Test.hs
- src/Input/Item.hs
This fixes a error in #271  and tests for the FromJSON and ToJSON
for Target.
Let me me know if anything looks off, I'm still finding my way around Haskell in general...
> Fix FromJSON and add test

- src/Action/Server.hs
- src/Input/Haddock.hs
- src/Input/Item.hs
> Prefix Target html index with a 's'

- src/Action/Search.hs
- src/Action/Server.hs
- src/General/Store.hs
- src/General/Util.hs
- src/Input/Cabal.hs
- src/Input/Download.hs
- src/Input/Haddock.hs
I am still in favour of `fail` over `errorIO` but this is the first draft what files would be affected by this change.
> Replace error in IO with errorIO

- src/General/Util.hs
- src/Input/Haddock.hs
Fixes #261
I confirm I am licensing your contribution under all licenses that apply to this project (see LICENSE) and that I have no patents covering your contribution.
> Add support for pattern synonyms in Haddock input

- src/General/Web.hs
Apologies for missing this in creating the original CSP.
> relax CSP to let plugin search work as before

- src/Action/Server.hs
- src/Output/Tags.hs
./src/Action/Server.hs:64:16: Suggestion: Replace case with maybe
Found:
case datadir of
Just d -> return d
Nothing -> getDataDir
Perhaps:
maybe getDataDir return datadir
> Replace case with maybe (hlint)

- src/Output/Types.hs
Partially addresses issue <https://github.com/ndmitchell/hoogle/issues/335>.
By raising this pull request you confirm you are licensing your contribution under all licenses that apply to this project (see LICENSE) and that you have no patents covering your contribution.
If you care, my PR preferences are at https://github.com/ndmitchell/neil#contributions, but they're all guidelines, and I'm not too fussy - you don't have to read them.
> Widen Name type to Word32

- src/Action/Generate.hs
- src/Input/Download.hs
I was having some problems understanding the logic of the download flag, I feel this is easier to grasp, feel free to ignore.
> Refactor Input/Download

- src/Action/Generate.hs
The command line parser accepts any flags in `generate`, but no warning is shown if user instructions are ignored.
This is a best-effort way of warning if a flag would be ignored, making it more user-friendly.
Ideally, this would be done before starting work, but I don’t see a good way to patch it into the command line parser; maybe by having an intermediate parsing step that parses into an ADT first and throws warnings for ignored arguments.
Another case I saw is that “--haskell” and “--frege” can both be set, but “--haskell” will always be ignored.
> Action/Generate: Best effort warnings when flags are ignored
