src/Recipe/Cabal.hs
It is possible to use Cabal 1.22 with GHC <7.10.
=> Use Cabal version, not GHC version for CPP guards

datadir/resources/hoogle.css, datadir/resources/hoogle.js, src/Web/Response.hs
Here is a simple implementation enabling keyboard navigation of results as is done by, e.g., [`rustdoc`](http://static.rust-lang.org/doc/master/std/index.html?search=cell).
I still don't consider this finished work as I worry that it might interfere too strongly with scrolling (which is more likely to be needed in hoogle results than with rustdoc) and the styling could be improved.
Thoughts?
=> [RFC] Keyboard selection

src/Action/Search.hs, src/Input/Hoogle.hs
Use the same escaping rules that Haddock does, to ensure that links to
specific types or values in Haddock documentation (eg, mapM_, (:+)) work
correctly.
=> Fix escaping for URL fragments (#103)

html/welcome.html
Fixes #72 , adds an example search for "+bytestring concat" on the welcome page.
=> Add package search example

datadir/examples.txt, src/Recipe/All.hs, src/Recipe/Keyword.hs
Changed the URL for "keywords" from http://www.haskell.org/haskellwiki/Keywords to http://wiki.haskell.org/Keywords in order to fix "hoogle data".
=> fixed URL for "keywords"

src/Console/All.hs
currently, hoogle convert only prints:
Skipped x warnings ...
but never (not even with --verbose) outputs what these warnings actually are which makes debugging harder
=> make hoogle convert --verbose print all the warnings

src/Console/All.hs
the --doc flag for convert is a little weird; it only supports http:// (and not https://) and for files it adds an extra /index.html
later, the code for showing the links strips everything from the last slash so if it's a file, we're supposed to put in the directory (since /index.html is added automatically), but for http, we're supposed to put the whole filepath (including index.html?) ... or spend some time tinkering to reverse engineer this and then add an extra slash at the end so nothing is stripped...
test plan:
```
> hoogle convert default.txt -d "file://foo/bar/"
> hoogle search -l a
Mod a :: Int -- file://foo/bar/Mod.html#v:a
> hoogle convert default.txt -d "foo/bar"
> hoogle search -l a
Mod a :: Int -- file:///foo/bar/Mod.html#v:a
> hoogle convert default.txt -d …
```
=> allow https:// protocol for links

hoogle.cabal, src/CmdLine/Type.hs, src/Web/Server.hs
`hoogle server --https --cert="my_cert.pem" --key="my_key.pem"` serves the hoogle pages over TLS
tested with a self-generated certificate:
* are we worried about pulling in this dependency?
* i have no idea whether this depends on particular versions of some packages
* if this is useful, i can also modify hoogle5 to support https
=> add option to run hoogle server over TLS

src/CmdLine/Type.hs, src/Web/Server.hs
again, i'll make sure i port this also to hoogle5
i also tried an ipv6-only option but when testing it ("!6"), hoogle was still accessible via ipv4 - i'm not sure whether that's a bug in some of the networking libraries...
=> enable support for IPv6

src/Action/Generate.hs
At least in the case of Nix---which has a function to automatically create a hoogle index for the libraries it's in the process of installing for you (which means you can't use `ghc-pkg list`)---it is helpful to be able to have hoogle recurse through a directory (which is actually a symlink farm to the documentation directories of the various libraries) looking for .txt files, rather than just looking shallowly.
=> Use a recursive directory traversal in generate

src/Action/Generate.hs
Addresses #184, at least in my testing.  It's also pretty darn obvious. :)
The question I could reasonably see it being worth asking is whether we should check and make sure that, say, index.html exists in the directory.
=> Use file URLs for local docs

html/index.html, src/Action/CmdLine.hs, src/Action/Server.hs
This adds a new `--home` flag, which allows you to specify the URL
linked to by the Hoogle logo in the upper left of every page.
This ameliorates the following frustrating scenario:
1. Launch `hoogle -p 8080 --local` (or similar)
2. Navigate to localhost:8080
3. Search for `foo` with your local Hoogle instance
4. You found what you want, so you instinctively click the Hoogle logo
in the upper left to get back to the home page.
5. Now you're at hoogle.haskell.org rather than localhost:8080
6. Either you notice, in which case you have to navigate back to your
local instance, or you don't notice, in which case you get very
confused as none of your local packages show up in search results.
=> Added `--home` flag to `server` command

src/Action/CmdLine.hs, src/Action/Generate.hs, src/Action/Test.hs
Patch generate command to accept the `--local' flag more than once, hence enabling Hoogle to generate docs for more than one packages at same database.
Note that with this patch, passing `--local <dir1> --local --local <dir2>` is allowed, and will fail with
```bash
hoogle: : getDirectoryContents: does not exist (No such file or directory)
```
This is not optimal, but it was done in Debian in order to keep backward compatibility (i.e., support both `--local` and `--local <dir>` as before). We could probably create a new flag, namely `--ghc-pkg` and drop the empty `--local` one. What do you think?
Closes #192: Allow indexing multiple local packages
=> Allow indexing multiple local packages

src/Action/Server.hs
Fixes #200.
It looks like the code in `Action.Server` has bit-rotten and it wasn't using the correct types for output. It was using a plain `OutputString` whereas `OutputHTML` would have been more appropriate at it causes the web server to send the appropriate `Content-Type`. I've changed those, which fixed the issue with text-browsers that I was seeing. 
I didn't touch the `OutputString` in the stats handler as I was not sure about the intended semantics of the output. It might be worth checking it and also searching for other occurrences of `OutputString` and checking if a more specific constructor (e.g. OutputHTML or OutputJSON) would be more appropriate.
=> Correct output semantics for the search server

src/Action/CmdLine.hs, src/Action/Generate.hs, src/Action/Server.hs
* `hoogle generate --haddock=path/to/doc` works similarly to `hoogle generate --local`, getting package info from a local ghc-pkg database, but uses `path/to/doc` as the canonical source of Haddock documentation. `path/to/doc` should be a path to the directory that contains the root `index.html` generated by `cabal haddock` or `stack haddock`. Paths stored in the database are relative to this root.
* `hoogle server --haddock=path/to/doc` is intended to be used with a database containing relative paths. In contrast to `hoogle server --local`, paths relative to the filesystem root are not allowed; only files from `path/to/doc` are served.
These features are intended to be used together, when you want to create a Hoogle index for your project in one place, then serve it somewhere else. This …
=> Support for a portable haddocks directory when indexing local projects

hoogle.cabal, src/Action/Search.hs, src/General/Util.hs, src/Hoogle.hs
We needed unHTML for Haskell IDE Engine.
=> Exposing unHTML

docs/Install.md
Using macOS Sierra, Version 10.12.5.
While setting up Hoogle in GHCi today, noticed that I needed to make this deviation from the existing instructions in order to get it working.
=> correction to GHCi Integration docs in script defining ':hoogle'

src/Action/CmdLine.hs
starting the webserver on a non privilege port is a sensible default for most applications, allows to execute hoogle as non root user without further ado
=> start hoogle on non privilege port by default

src/Action/Search.hs, src/Output/Tags.hs
Issue described in #215 
Also fixes a bug where package names with upper case letters(QuickCheck, HaRe etc.) wouldn't be found in the db.
=> Don't output results when specified module/package/category not found in db.

src/Action/CmdLine.hs, src/Action/Server.hs
Building a binary that contains a hoogle server has hard-coded paths embedded in the binary. When deploying this binary to other machines, the full paths generated from `Paths_hoogle` may not exist. This provides a command line override for the location of the local resources.
=> Command flag for overriding data directory in servers

html/hoogle.js
Here I fix search plugin installation. It  It did not work correctly since URI to OpenSearch descriptor and prefix URl were concatenated in wrong way. The conditions to add prefix to URI is a bit messy so here I provide some details about issue. There are a three kinds of URLs they are
1. schemafull URLs like `https://hoohle.haskell.org/some/uri/here` (`://` is in)
2. schemaless URLs like `//git.dsn/some/uri/here` (`//` is the prefix)
3. URI string like `/res/search.xml` or `res/search.xml?domain=...`
So we should check that the first and the senсond conditions are false simultaneously. If the last one statement correct then we should concatenate URL prefix and URI string.
=> [#123] Fix search plugin setup.

src/Action/Server.hs
When serving with `--local`, replace `file://` URLs in files that are
served from disk with relative `file/` URLs.
Fix #236 
Haven't been able to test this because of problems with zlib.h not being found even though there's multiple on my system (arch linux).
Decided to open the PR already anyway for feedback. I'm not sure about the performance implications of readFile and the literal string replacement I"m doing currently, a more proper way would be to parse URLs from the file and replace them with `showURL True` applied to them.
=> Replace `file://` URLs with relative URLs

CHANGES.txt
The most recent entry contained a typo: 2.0.17.1 instead of 5.0.17.1
=> Fix Changes.txt 2.0.17.1 version number typo

html/hoogle.css, html/index.html
Using a more modern method based on the flex properties to keep the footer sticking to the bottom of the page but not overlap the last result after the results are updated dynamically.
I did some minor testing after applying the same (at least I hope so) changes in a web inspector for hoogle.haskell.org so some more thorough testing is advisable.
Credit goes to @entuland.
=> Footer overlap

src/Action/Server.hs
src/Action/Server.hs:206:49: warning: [-Wdeprecations]
In the use of for (imported from Data.List.Extra):
Deprecated: Use flip map directly, since this function clashes with Data.Traversable.for
By raising this pull request you confirm you are licensing your contribution under all licenses that apply to this project (see LICENSE) and that you have no patents covering your contribution.
If you care, my PR preferences are at https://github.com/ndmitchell/neil#contributions, but they're all guidelines, and I'm not too fussy - you don't have to read them.
=> Fixup deprecation warning about for function.

.stylish-haskell.yaml, src/Action/Search.hs, src/General/Store.hs, src/Output/Types.hs, todo3.txt
This is a first go at adding type search on top of the fingerprint filtering. The query (or some simple variations of it) is checked against the proposed answer signature by attempting to unify the answer with the query, keeping type variables in the query fixed. The amount of "unification work" needed gives a cost, that is later combined with the fingerprint cost and a heuristic about the number of abstract constraints.
I made a list of test cases (see `todo3.txt`) that did not previously work, to help mark progress as type search is added. Some of the test cases come from github issues, others are things I came across on stackoverflow, twitter, etc. Even this simple type search seems to improve the results quite a bit, compared to fingerprint-only search.
My editor setup made some …
=> Type search

html/welcome.html
Hoogle 5 does seem to support type search now. I haven't checked whether support is as complete as it was 5 years ago, but even if not, I don't think we need this banner anymore.
=> Scary banner no longer needed

src/Action/Search.hs
This mostly involved some previously-expected-failures turning into
successes, but there was a regression where Yesod's `lookupJust :: (Eq a,
Partial) => a -> [(a,b)] -> b` is now getting preferred over `base`'s `lookup :: Eq
a => a -> [(a,b)] -> Maybe b`.
Fixes #282
=> Update expected test results for 8.6 base.

src/General/Web.hs
Turns out the CSP entry has been deprecated in favour of the header,
even though the header was there before.
Having the CSP entry does not actively harm anything as far as I can see, but it _is_ redundant and will produce a warning as an unrecognized entry in some browsers.
It looks like the documentation I followed to create the orginal CSP was outdated in that regard.
=> remove reflected-xss CSP entry

src/Action/CmdLine.hs, src/General/Web.hs
Currently when trying to run the server on localhost, the CSP will force trying to load the assets through HTTPS. This doesn't work.
This PR adds a command-line flag to disable all security headers.
=> optionally disable security headers

.ghci, src/Action/Server.hs, src/General/Web.hs
There is a bug in the current path handling code that allows an attacker with direct access to the hoogle server to force it to return files it has access to. This does *not* seem to work through an nginx proxy such as the setup on hoogle.haskell.org.
Repro on current master:
```                                                                                                                                                                                    
$ git clone git@github.com:ndmitchell/hoogle.git
Cloning into 'hoogle'...
[...]
$ cd hoogle
$ git rev-parse HEAD
4fc77219521055ac96eca9908b4fb9a63ec9a0c5
$ stack init
[...]
* Matches nightly-2019-05-27
Selected resolver: nightly-2019-05-27
Initialising configuration using resolver: nightly-2019-05-27
Total number of user packages …
```
=> Fix traversal bug

src/Output/Types.hs
When comparing fingerprints, instead of getting differences of negative numbers
like -1 we were getting 255 because of overflowing. This meant we had dead code
for the conditions to give a cost of 1000 for removing an arity and a cost of 12
for removing a term. Now we correctly execute these code paths.
Given the following:
Query: Bool -> Bool -> Bool
Sig String: Bool -> Bool -> Bool
Sig Name: C65532 -> C65532 -> C65532
Fingerprint: arity=2, terms=3, rarity=C65532 _ _
We used to get:
Answer 1: Bool -> Bool
Sig String: Bool -> Bool
Sig Name: C65532 -> C65532
Fingerprint: arity=1, terms=2, rarity=C65532 _ _
Cost: X, no match
Explain: X , X terms 255 different, 0 term in common C65532, 0 term in
common _, 0 term in common _, 0 term in common C65532, 0 term in common _, 0
term in common _
Now …
=> Fix overflows of arity and term differences

src/General/Web.hs
Fixes #314 
This happens only when run with `--local` flag and a package name is clicked as
it doesn't have a specific file path in the URL.
`decodePathSegments` adds an empty string if the path ends with a `/`
And because of this `all (== '.') ""` returns `True` which then makes it a bad
path according to the previous logic.
=> Fix `Bad URL` error when a package is clicked

src/Action/CmdLine.hs, src/Action/Search.hs
Fixes #287 
Add `--json` flag to get results as JSON
=> Add support for results as JSON while searching through commandline

src/Action/Server.hs
Currently:
1. search for `&&`
2. click on one of the links in the "Packages" list on the left
3. oops: `Bad URL: /?hoogle=&&%20package:base&amp;scope=set:stackage"`
This PR fixes that (and removes double-escaping of `&`).
=> fix escaping in packages list (on the left)

src/General/Util.hs
I noticed that `escapeURL` doesn't properly handle ord < 10 or > 255 (so mostly unicode).
This is probably the easiest way to fix it.
=> fix escapeURL

src/General/Web.hs
fixes #324
I haven't exhaustively tested whether this breaks anything, but it works locally with:
```
$ cat misc/sample-data/foo-1.0/foo.txt
@url http://eghmitchell.co.uk/
@package foo
@version 1.0
module Foo
@url #a_foo
猫 :: String
x猫 :: String
neko :: String
(≠) :: Eq a => a -> a -> Bool
(/=) :: Eq a => a -> a -> Bool
$ cabal run hoogle -- generate --local=misc/sample-data/foo-1.0/
$ cabal run hoogle -- server -p 8888 --host 127.0.0.1
```
--> http://localhost:8888/?hoogle=≠ works :)
I did find that `猫` is not indexed by `generate`, but that's a bug in `haskell-src-exts`.
=> fix unicode search

html/index.html
The dot in the action fields creates URLs like `/./?hoogle=` when the form is submitted (without JavaScript). Those URLs return 404's
By raising this pull request you confirm you are licensing your contribution under all licenses that apply to this project (see LICENSE) and that you have no patents covering your contribution.
If you care, my PR preferences are at https://github.com/ndmitchell/neil#contributions, but they're all guidelines, and I'm not too fussy - you don't have to read them.
=> Empty action attribute

docs/API.md, src/Action/Server.hs, src/Input/Item.hs
After discussing in https://github.com/ndmitchell/hoogle/issues/337, I decided to follow the suggestion of having a new query parameter called `format`, that currently supports only the `text` value (which will rip out any HTML code in the results). It only works if the request is made in `json` mode, otherwise it's ignored (I didn't think it was necessary to change it for other modes, but I'm surely open to discussions).
Other than that, maybe adding some tests and instructions to https://github.com/ndmitchell/hoogle/blob/master/docs/API.md would be good.
I'm open to any comments!
=> Add option to get plain text on JSON responses

src/Action/Generate.hs, src/Action/Search.hs
This will take the name of the directory that the `--local` flag is passed and create a set named after it.
This doesn't handle all the cases I would like it to\*, but it's a good basic start and more complex functionality can be built on it in the future.
Addresses the basic case of #341 .
---
\* The biggest thing being having the same package in multiple sets, which isn't handled at all and results in the "higher priority" package in the [sort that's used to get the highest version package](https://github.com/ndmitchell/hoogle/blob/master/src/Action/Generate.hs#L127-L131) being the thing that determines the set it's in.
=> Have --local flag generate a set with the directory name

src/Action/Generate.hs
This improves the functionality introduced #342 and constitutes more progress on #341 .
Now packages can be in multiple sets.
Basically, since you're generating a bare package for .txt file documentation found, it's fine to just mappend them. If you did this with cabal generated ones it would be a mishmash, but we're not!
=> Improve `--local` set functionality

src/Input/Cabal.hs
ghc-pkg output format changes across GHC versions. hoogle generate was
broken for GHC 8.8.3 because it wrongly parsed the package name and
'haddock-html:' resulting in no documentation being found at all.
This PR partially addresses #350.
=> Partially fixed ghc-pkg output parsing for GHC 8.8

src/Action/CmdLine.hs, src/Action/Test.hs
The without this, it is impossible to run tests in a sandbox environment such as that used by gentoo's portage package manager.
Signed-off-by: Wolfgang E. Sanyer <WolfgangESanyer@gmail.com>
By raising this pull request you confirm you are licensing your contribution under all licenses that apply to this project (see LICENSE) and that you have no patents covering your contribution.
If you care, my PR preferences are at https://github.com/ndmitchell/neil#contributions, but they're all guidelines, and I'm not too fussy - you don't have to read them.
=> Add flag to disable network tests.

src/Action/Test.hs, src/General/Web.hs
This fixes another directory traversal for paths of the form
http://localhost:8080/..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2fetc/nixos/configuration.nix.
Also added a bunch of tests for the validation logic since I really
don’t trust it given that this is the second issue after the first one
got fixed almost two years ago in #306.
I’m also starting to wonder if hoogle should have an option to just
disable the generic file server completely. In anything some type of
production setup, serving the required static assets via nginx seems
like a much more sensible solution than trying to get this right in
hoogle.
By raising this pull request you confirm you are licensing your contribution under all licenses that apply to this …
=> Fix URL validation logic

README.md
The link to subscribe is dead, and Ubiquity isn't usable in any modern version of Firefox.
=> Remove "Firefox Ubiquity" section in README.md

README.md
You mentioned in #369 that the README could use some love, so I've done my best to clean it up a bit.
[Preview of the new README.md](https://github.com/lambdadog/hoogle/blob/ashlynn/readme-tlc/README.md)
This consists of, largely:
- Replacing dead links and updating ones which redirect or are now at a new location
+ Pointing to your new homepage (https://ndmitchell.com) over the nonexistent `community.haskell.org` one.
+ Using more modern `doi.org` links over `portal.acm.org` ones
+ etc.
- Using HTTPS over HTTP where possible
- Removing the Hoogle 4->5 section that's no longer relevant
- Correcting sections that are now incorrect
+ Updating instructions in Firefox section
+ Update "The Source Code" section to refer to GitHub and the GitHub issue tracker
+ etc.
- Redo "Folders" section and …
=> Cleanup on README.md

src/Action/CmdLine.hs, src/Action/Search.hs
Reason: in situation where one cannot use the shell post-processing it is
easier to output one entry per one line for which JSONL is suitable.
This PR introduces the support in hoogle
=> Allow for JSONL output for search command

html/hoogle.css, src/Action/Server.hs
When going through the result page navigating with tab, if you wanna go from search input to results, you need to tab through the left anchors.
Rapid access to results seems more important, especially as a user navigating with keyboard could be more inclined to directly typing those left search criteria rather than selecting them with tab.
I did not open an issue about it, so i'm making the proposition as a pull request directly.
I am available if you have any feedback.
=> Move results before left anchors in tab focus order

src/Action/Generate.hs
I think that url bindings  of `stackageLts` and `stackageNightly` variables are inverted.
=> Fix stackage lts and nightly urls in Generate.hs

src/Action/Generate.hs
Seven years ago, mtl docs were broken (#251) and needed to be hacked around.
Now they're fine, so we can remove the hack.
=> Undo mtl hack

src/Action/Server.hs
This addresses https://github.com/ndmitchell/hoogle/issues/442
It's a bit of a blunt hammer, and another solution would be nicer, but for now I feel this is necessary given the traffic load on hoogle, and will get our main instance in much better shape.
=> no leftlinks if query specifier given
